feat: oauth github flow'
GlueOps/signup pull request #1
Opened 2024-05-27 21:55 UTC by fernandoataoldotcom

2024-05-27 23:19 UTC, venkatamutyala requested changes

2024-05-27 23:19 UTC, venkatamutyala commented on Dockerfile
> +CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
I think you can set the port as an environment variable `FLASK_RUN_PORT`

2024-05-28 03:01 UTC, fernandoataoldotcom commented on Dockerfile
> +CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
> I think you can set the port as an environment variable `FLASK_RUN_PORT`

can you point me to the docs you found for this?
I tested and didn't get it working - also, seeing this: https://chatgpt.com/share/97c134b0-4e7c-447d-9a13-c6b22898e8c3

fwiw, I think `EXPOSE 5000` and `ENV FLASK_APP=app.py` also don't do anything so I dropped them

2024-05-30 15:50 UTC, venkatamutyala requested changes

2024-05-30 15:50 UTC, venkatamutyala commented on Dockerfile
> +CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
People mention not being able to find the docs though: https://stackoverflow.com/questions/41940663/how-can-i-change-the-host-and-port-that-the-flask-command-uses

2024-05-30 15:50 UTC, venkatamutyala commented on app.py
> +    app.secret_key = os.env('APP_SECRET_KEY')
How is this different than the other env variables like client_id and client_secret? Also you are using os.env, if it doesn't exist i think it errors immediately. getenv doesn't return an error: https://stackoverflow.com/a/41626355

2024-05-30 15:50 UTC, venkatamutyala commented on app.py
> +    logger.exception('could not retrieve environment secret')
i don't think this will get executed per os.getenv vs os.env https://stackoverflow.com/a/41626355

2024-05-30 15:50 UTC, venkatamutyala commented on app.py
> +    app.run(host='0.0.0.0', port=5000, debug=True)
I think you will want to default to the environment variables instead of hardcoding it?

2024-05-30 15:56 UTC, fernandoataoldotcom commented on Dockerfile
> +CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
I think that's for the flask dev server and not the gunicorn WSGI

2024-05-30 16:48 UTC, fernandoataoldotcom commented on app.py
> +    logger.exception('could not retrieve environment secret')
ya, good call, these should be .get, updated

2024-05-30 16:49 UTC, fernandoataoldotcom commented on app.py
> +    app.run(host='0.0.0.0', port=5000, debug=True)
for port or for all of them?

2024-05-30 16:50 UTC, fernandoataoldotcom commented on app.py
> +    app.secret_key = os.env('APP_SECRET_KEY')
this is different because the app can function with a randomly generated key, but is ideally a persistent value per application

the app won't function at all without client_id and client_secret

2024-05-30 21:03 UTC, venkatamutyala approved these changes

2024-06-03 22:35 UTC, merged